spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: ''
  h2:
    console:
      enabled: 'true'
  application:
    name: sick
server:
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: always
